---
## Author
author:
  name: Бородин Дмитрий Алексеевич
  studID: 1132250461
  group: НПБд-03-25
  email: 1132250461@pfur.ru
  license: "CC BY"
---

## Title
title: "Отчёт по лабораторной работе №2"
subtitle: "Дисциплина: Архитектура компьютера"
---

# Цель работы

Целью работы является изучение идеологии и применения средств контроля версий, приобретение практических навыков по работе с системой контроля версий git.

# Выполнение лабораторной работы

## 1. Базовая настройка git

Делаем предварительную конфигурацию git [рис. @fig-001] [рис. @fig-002] [рис. @fig-003]

- [Задаём имя и email репозитория](./image/1.jpg){#fig:001 width=70%}
- [Настраиваем utf-8 в выводе сообщения git](./image/2.jpg){#fig:002 width=70%}
- [Задаём имя начальной ветки master, устанавливаем настройку autocrlf и параметр safecrlf](./image/3.jpg){#fig:003 width=70%}

## 2. Создание SSH-ключа

- [Генерируем пару ключей](./image/4.jpg){#fig:004 width=70%}
- [Копируем ключ из локальной консоли в буфер обмена](./image/5.jpg){#fig:005 width=70%}
- Заходим в свой аккаунт на сайте github [рис. @fig-006]

## 3. Клонирование репозитория

- [Клонируем репозиторий с помощью SSH](./image/6.jpg){#fig:006 width=70%}
- [Структура файлов и каталогов после клонирования](./image/7.jpg){#fig:007 width=70%}

## 4. Первые коммиты, создание структуры проекта

- [Инициализируем файлы, делаем первый commit](./image/8.jpg){#fig:008 width=70%}
- [Пушим изменения на GitHub](./image/9.jpg){#fig:009 width=70%}

# Самостоятельная работа

## 5. Работа с ветками и слияние изменений

- [Создаём отдельную ветку, вносим изменения, коммитим](./image/10.jpg){#fig:010 width=70%}
- [Выполняем merge и разрешаем потенциальные конфликты](./image/11.jpg){#fig:011 width=70%}

## Комментарии и выводы

- Все этапы лабораторной работы выполнены успешно.
- Репозиторий склонирован и настроен с использованием SSH.
- Практические навыки работы с git и GitHub получены в полном объёме.

# Общий вывод

Поставленная цель работы достигнута: освоена базовая и самостоятельная работа с системой контроля версий git, ключевой функционал проверен на практике, приобретён опыт взаимодействия с удалёнными репозиториями через SSH-ключи.



